name: SilkSpawners
main: me.petterim1.silkspawners.Main
version: "${pom.version}"
api: ["1.0.0"]
author: PetteriM1
softdepend: ["MobPlugin"]

permissions:
  silkspawners.use:
    description: "Use SilkSpawners"
    default: true
